# Generated by Django 4.2 on 2024-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Admin', 'Admin'), ('Client', 'Client'), ('Superadmin', 'Superadmin')], default='Admin', max_length=50),
        ),
    ]
