# Generated by Django 4.2 on 2024-08-14 05:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(max_length=128)),
                ('car_title', models.CharField(max_length=128)),
                ('variant', models.CharField(max_length=128)),
                ('vin', models.CharField(max_length=128)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('make_year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ownership', models.CharField(max_length=128)),
                ('registration_location', models.CharField(max_length=128)),
                ('insurance', models.CharField(max_length=128)),
                ('insurance_validity', models.DateField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=128)),
                ('engine_capacity', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('condition', models.CharField(max_length=128)),
                ('key_features', models.CharField(max_length=128)),
                ('convenience_feature', models.CharField(max_length=128)),
                ('km_driven', models.PositiveIntegerField()),
                ('registry_year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], max_length=20)),
                ('seller_name', models.CharField(max_length=128)),
                ('contact_no', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('car_image', models.ImageField(upload_to='car_images')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
