# Generated by Django 4.2 on 2024-09-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rto_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
