# Generated by Django 4.2 on 2024-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='warranty',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
