# Generated by Django 4.2 on 2024-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
