# Generated by Django 4.2 on 2024-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_testdrive'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_structure_damage',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='flodded_body',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
