# Generated by Django 4.2 on 2024-08-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_body_structure_damage_car_flodded_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='flodded_body',
            new_name='flooded_body',
        ),
    ]
