# Generated by Django 4.2 on 2024-09-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_inquiry_is_approved_testdrive_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
